name: Build

on:
  push:
    branches: [ 'main' ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: pagdot
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch version numbers
        run: "bash .github/workflows/fetch_vers.sh"

      - name: Build and push containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:v${{ env.RESTIC_VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:version-v${{ env.RESTIC_VERSION }}
            ${{ env.IMAGE_NAME }}:v${{ env.RESTIC_VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:v${{ env.RESTIC_VERSION }}
