name: Build

on:
  push:
    branches: [ 'main' ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *' # every day 5am

env:
  IMAGE_NAME: ${{ github.repository }}
  RESTIC_VERSION: ""  # Filled later
  RCLONE_VERSION: ""  # Filled later
  TAGS: ""            # Filled later

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: pagdot
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch RESTIC_VERSION and RCLONE_VERSION
        run: "bash .github/workflows/fetch_vers.sh"

      - name: Generate TAGS
        run: "bash .github/workflows/gen_tags.sh"

      - name: Build and push containers
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.TAGS }}
